source 'http://rubygems.org'

gem 'rails', '~> 3.1.0.rc'
gem 'sqlite3'

gem 'github-widget', :path => '../'
gem 'sproutcore-rails', :git => 'git://github.com/GutenYe/sproutcore-rails.git', :branch => 'source'
gem 'github-api-rails', :git => 'git://github.com/GutenYe/github-api.git', :branch => 'rails'

# Asset template engines
gem 'sass-rails', "~> 3.1.0.rc"
gem 'coffee-script'
gem 'uglifier'

# JavasScript libs
gem 'jquery-rails'
gem 'modernizr-rails'

# Stylesheet libs
# gem 'blueprint-rails'

# Ajax request CoffeeScript support
# gem 'coffeebeans'

# Heroku deployment requirements
# group :production do
#   gem 'therubyracer-heroku'
#   gem 'pg'
# end


# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end
